language: node_js

os:
  - osx
  - linux

arch:
  - amd64
  - arm64

node_js:
  - '10'
  - '11'
  - '12'
  - '13'
  - '14'

install:
  - yarn

script:
  - yarn test

after_success:
  - yarn global add codecov
  - codecov
